// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rykrzypcwjjunlmjryec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5a3J6eXBjd2pqdW5sbWpyeWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjA0MzYsImV4cCI6MjA3MDAzNjQzNn0.FhNa3uEOqhxn_dqYx1yZn0a0yyTb1N3lR5qzhNhRLYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});